[package]
name = "beatriz"
version = "0.1.0"
authors = ["Alyx Mote <figments@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.9.0-rc.1"